print("Welcome to the Gaaaammmeee show!!Press enter to continue!!")
input("")
print("Where we ask questions about YOU!")
input("")
their_name = input("Whats your your beautiful name?!!")
print(f"Hi {their_name},what a cool name")
input("")
print("I hope yourrrrrr ready!!!")
input("")
print("First question!!!")
their_answer = input("What do you do for fun!?")
print(f"Wow you do {their_answer}, I never knew people did that!")
input("")
print("Were off to a great start!!")
input("")
print("Second question")
input("")
their_answer = input("What is your favorite food??")
print(f"MMM {their_answer} sounds yummy")
input("")
